---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents relatifs à Amazon FSX pour NetApp ONTAP
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez Amazon FSX pour NetApp ONTAP
      url: "/start/concept-fsx-aws.html"
    - title: Démarrage rapide
      url: "/start/task-getting-started-fsx.html"
    - title: Configurez les autorisations
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: Créer ou découvrir un environnement de travail
      url: "/use/task-creating-fsx-working-environment.html"
  - title: Gérer un système de fichiers FSX pour ONTAP
    url: "/use/task-manage-working-environment.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/support/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
