---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: 'Amazon FSX pour NetApp ONTAP est un service entièrement géré qui permet aux clients de lancer et d"exécuter des systèmes de fichiers optimisés par le système d"exploitation du stockage ONTAP de NetApp. FSX pour ONTAP offre les mêmes fonctionnalités, performances et administration que les clients NetApp utilisent l"environnement sur site, avec la simplicité, l"agilité, la sécurité et l"évolutivité d"un service AWS natif.' 
---
= Découvrez Amazon FSX pour NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX pour NetApp ONTAP"^] Est un service entièrement géré qui permet aux clients de lancer et d'exécuter des systèmes de fichiers optimisés par le système d'exploitation du stockage NetApp ONTAP. FSX pour ONTAP offre les mêmes fonctionnalités, performances et administration que les clients NetApp utilisent l'environnement sur site, avec la simplicité, l'agilité, la sécurité et l'évolutivité d'un service AWS natif.



== Caractéristiques

* Nul besoin de configurer ou de gérer des périphériques, logiciels ou sauvegardes de stockage.
* Prise en charge des protocoles CIFS, iSCSI, NFSv3, NFSv4.x et SMB v2.0 - v3.1.1.
* Capacité de stockage des données économique et quasi illimitée sur le Tier de stockage disponible rarement utilisé (IA).
* Exécution certifiée sur des applications sensibles à la latence, y compris Oracle RAC.
* Vous avez le choix entre un bundle et une facturation à l'utilisation.




== Fonctions supplémentaires dans BlueXP

* FSX pour ONTAP est pris en charge lorsque BlueXP est utilisé en mode _standard_ ou _restricted_.
+
** Le mode standard exploite la couche SaaS BlueXP pour offrir des fonctionnalités complètes.
** Le mode restreint est disponible pour les organisations qui ont des restrictions de connectivité.
+
Reportez-vous à la section link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modes de déploiement BlueXP"^] pour en savoir plus.



* À l'aide de link:https://docs.netapp.com/us-en/bluexp-family/["BlueXP"^] Enfin, un connecteur dans AWS vous permet de créer et de gérer des volumes, de répliquer des données et d'intégrer FSX pour ONTAP avec des services cloud NetApp, tels que la classification BlueXP et la copie et la synchronisation BlueXP.
* Avec la technologie basée sur l'intelligence artificielle (IA), la classification BlueXP vous aide à comprendre le contexte des données et à identifier les données sensibles qui résident dans vos comptes FSX pour ONTAP. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["En savoir plus >>"^].
* Avec la copie et la synchronisation BlueXP, vous pouvez automatiser la migration des données vers n'importe quelle cible dans le cloud ou sur site. https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["En savoir plus >>"^]




== Le coût

Votre compte FSX pour ONTAP est géré par AWS et non par BlueXP. Reportez-vous à la section https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Guide de démarrage d'Amazon FSX pour NetApp ONTAP"^].

L'utilisation du connecteur dans AWS et les services de données facultatifs tels que la copie et la synchronisation BlueXP et la classification BlueXP entraînent des coûts supplémentaires.



== Régions prises en charge

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Affichez les régions Amazon prises en charge."^]



== Obtenir de l'aide

Amazon FSX pour NetApp ONTAP est une solution propriétaire AWS. Pour toute question ou tout problème de support technique associé à votre système de fichiers FSX for ONTAP, à votre infrastructure ou à toute solution utilisant ce service, utilisez le centre de support de votre console de gestion AWS pour ouvrir un dossier de support avec AWS. Sélectionnez le service “FSX pour ONTAP” et la catégorie appropriée. Fournissez les informations restantes nécessaires pour créer un dossier de demande de support AWS.

Pour des questions générales sur les solutions et services de stockage BlueXP ou BlueXP, vous pouvez commencer par le chat en ligne BlueXP.

Pour les problèmes de support technique spécifiques aux solutions et services de stockage BlueXP ou BlueXP, vous pouvez ouvrir un ticket de support NetApp à l'aide du numéro de série de votre compte BlueXP. Vous devez le faire link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["Enregistrez votre compte BlueXP"^] pour activer le support.
